module.exports = {
    title: 'Apple Macbook Air - 13" 256GB',
    price: 'Rs 265,900',
    image: 'https://myshop.pk/pub/media/catalog/product/cache/26f8091d81cea4b38d820a1d1a4f62be/a/p/apple-macbook-air-myshop.pk03_2_1_1.jpg',
    tableData: {
      'Product Type': 'Laptop',
      Availability: 'Same Day Delivery',
      Series: 'Apple. Macbook Air M1',
      Model: 'MGN63LL-MGND3LL-MGN93LL',
      'OS Version': 'macOS',
      Processor: 'Apple',
      Generation: '1st Generation',
      Speed: 'M1, 8 Core CPU, 7 Core GPU',
      'Screen Size': '13.3"',
      'Max Res': '2560 x 1600  :WQXGA',
      RAM: '8 GB',
      Drive: '256 GB',
      Type: 'SSD',
      Optical: 'No Optical Drive',
      'Graphics Card': 'Apple M1 GPU',
      Memory: 'System Shared',
      Features: 'Wifi, WebCam, Bluetooth, Backlit Keyboard',
      'External Ports': 'Headphone/Mic combo, USB-C',
      Dimensions: '1.61 x 30.41 x 21.24 cm',
      Weight: '2.84 lbs',
      'Manufacturer Link': 'Additional Information',
      Warranty: 'International / Manufacturer',
      'Color Detail': 'Space Grey  MGN63LL, Gold  MGND3LL & Silver  MGN93LL'
    }
  }